# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_frame_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QPushButton {\n"
"    min-height: 38px;\n"
"    padding: 8px 18px;\n"
"\n"
"    color: #C9D7FF;\n"
"    background-color: rgba(18, 26, 48, 210);\n"
"\n"
"    border: 1px solid rgba(80, 130, 255, 90);\n"
"    border-radius: 10px;\n"
"\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(38, 56, 105, 230);\n"
"\n"
"    border: 1px solid rgba(90, 170, 255, 180);\n"
"}\n"
"\n"
"/* 鼠标按下 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(25, 38, 78, 240);\n"
"    border: 1px solid rgba(120, 210, 255, 220);\n"
"    padding-top: 10px;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* checkable 选中状态 */\n"
"QPushButton:checked {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #2563EB,\n"
"        stop:0.55 #7C3AED,\n"
"        stop:1 #06B6D4\n"
"    );\n"
"\n"
"    border: 1px solid rgba(180, 230, 255, 230);\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* 选中后再悬停 */\n"
"QPushButton:checked:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3B82F6,\n"
"        stop:0.55 #8B5CF6,\n"
"        stop:1 #22D3EE\n"
"    );\n"
"\n"
"    border: 1px solid rgba(220, 250, 255, 255);\n"
"}\n"
"\n"
"/* 禁用状态 */\n"
"QPushButton:disabled {\n"
"    color: rgba(180, 190, 210, 90);\n"
"    background-color: rgba(30, 35, 45, 120);\n"
"    border: 1px solid rgba(120, 130, 150, 60);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_navi_1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_navi_1.sizePolicy().hasHeightForWidth())
        self.pb_navi_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pb_navi_1.setFont(font)
        self.pb_navi_1.setStyleSheet("QPushButton {\n"
"    min-height: 38px;\n"
"    padding: 8px 18px;\n"
"\n"
"    color: #C9D7FF;\n"
"    background-color: rgba(18, 26, 48, 210);\n"
"\n"
"    border: 1px solid rgba(80, 130, 255, 90);\n"
"    border-radius: 10px;\n"
"\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(38, 56, 105, 230);\n"
"\n"
"    border: 1px solid rgba(90, 170, 255, 180);\n"
"}\n"
"\n"
"/* 鼠标按下 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(25, 38, 78, 240);\n"
"    border: 1px solid rgba(120, 210, 255, 220);\n"
"    padding-top: 10px;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* checkable 选中状态 */\n"
"QPushButton:checked {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #2563EB,\n"
"        stop:0.55 #7C3AED,\n"
"        stop:1 #06B6D4\n"
"    );\n"
"\n"
"    border: 1px solid rgba(180, 230, 255, 230);\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* 选中后再悬停 */\n"
"QPushButton:checked:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3B82F6,\n"
"        stop:0.55 #8B5CF6,\n"
"        stop:1 #22D3EE\n"
"    );\n"
"\n"
"    border: 1px solid rgba(220, 250, 255, 255);\n"
"}\n"
"\n"
"/* 禁用状态 */\n"
"QPushButton:disabled {\n"
"    color: rgba(180, 190, 210, 90);\n"
"    background-color: rgba(30, 35, 45, 120);\n"
"    border: 1px solid rgba(120, 130, 150, 60);\n"
"}")
        self.pb_navi_1.setCheckable(True)
        self.pb_navi_1.setAutoExclusive(True)
        self.pb_navi_1.setObjectName("pb_navi_1")
        self.horizontalLayout_3.addWidget(self.pb_navi_1)
        self.pb_navi_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_navi_2.sizePolicy().hasHeightForWidth())
        self.pb_navi_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pb_navi_2.setFont(font)
        self.pb_navi_2.setStyleSheet("QPushButton {\n"
"    min-height: 38px;\n"
"    padding: 8px 18px;\n"
"\n"
"    color: #C9D7FF;\n"
"    background-color: rgba(18, 26, 48, 210);\n"
"\n"
"    border: 1px solid rgba(80, 130, 255, 90);\n"
"    border-radius: 10px;\n"
"\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(38, 56, 105, 230);\n"
"\n"
"    border: 1px solid rgba(90, 170, 255, 180);\n"
"}\n"
"\n"
"/* 鼠标按下 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(25, 38, 78, 240);\n"
"    border: 1px solid rgba(120, 210, 255, 220);\n"
"    padding-top: 10px;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* checkable 选中状态 */\n"
"QPushButton:checked {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #2563EB,\n"
"        stop:0.55 #7C3AED,\n"
"        stop:1 #06B6D4\n"
"    );\n"
"\n"
"    border: 1px solid rgba(180, 230, 255, 230);\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* 选中后再悬停 */\n"
"QPushButton:checked:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3B82F6,\n"
"        stop:0.55 #8B5CF6,\n"
"        stop:1 #22D3EE\n"
"    );\n"
"\n"
"    border: 1px solid rgba(220, 250, 255, 255);\n"
"}\n"
"\n"
"/* 禁用状态 */\n"
"QPushButton:disabled {\n"
"    color: rgba(180, 190, 210, 90);\n"
"    background-color: rgba(30, 35, 45, 120);\n"
"    border: 1px solid rgba(120, 130, 150, 60);\n"
"}")
        self.pb_navi_2.setCheckable(True)
        self.pb_navi_2.setAutoExclusive(True)
        self.pb_navi_2.setObjectName("pb_navi_2")
        self.horizontalLayout_3.addWidget(self.pb_navi_2)
        self.pb_navi_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_navi_3.sizePolicy().hasHeightForWidth())
        self.pb_navi_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pb_navi_3.setFont(font)
        self.pb_navi_3.setStyleSheet("QPushButton {\n"
"    min-height: 38px;\n"
"    padding: 8px 18px;\n"
"\n"
"    color: #C9D7FF;\n"
"    background-color: rgba(18, 26, 48, 210);\n"
"\n"
"    border: 1px solid rgba(80, 130, 255, 90);\n"
"    border-radius: 10px;\n"
"\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(38, 56, 105, 230);\n"
"\n"
"    border: 1px solid rgba(90, 170, 255, 180);\n"
"}\n"
"\n"
"/* 鼠标按下 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(25, 38, 78, 240);\n"
"    border: 1px solid rgba(120, 210, 255, 220);\n"
"    padding-top: 10px;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* checkable 选中状态 */\n"
"QPushButton:checked {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #2563EB,\n"
"        stop:0.55 #7C3AED,\n"
"        stop:1 #06B6D4\n"
"    );\n"
"\n"
"    border: 1px solid rgba(180, 230, 255, 230);\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* 选中后再悬停 */\n"
"QPushButton:checked:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3B82F6,\n"
"        stop:0.55 #8B5CF6,\n"
"        stop:1 #22D3EE\n"
"    );\n"
"\n"
"    border: 1px solid rgba(220, 250, 255, 255);\n"
"}\n"
"\n"
"/* 禁用状态 */\n"
"QPushButton:disabled {\n"
"    color: rgba(180, 190, 210, 90);\n"
"    background-color: rgba(30, 35, 45, 120);\n"
"    border: 1px solid rgba(120, 130, 150, 60);\n"
"}")
        self.pb_navi_3.setCheckable(True)
        self.pb_navi_3.setAutoExclusive(True)
        self.pb_navi_3.setObjectName("pb_navi_3")
        self.horizontalLayout_3.addWidget(self.pb_navi_3)
        self.verticalLayout.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_navi_1.setText(_translate("MainWindow", "导航至页面1"))
        self.pb_navi_2.setText(_translate("MainWindow", "导航至页面2"))
        self.pb_navi_3.setText(_translate("MainWindow", "导航至页面3"))
