# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_test01_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(984, 784)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_contour_workflow = QtWidgets.QFrame(Form)
        self.frame_contour_workflow.setStyleSheet("#frame_contour_workflow {\n"
"    background: #f6f9fc;\n"
"    border: 1px solid #c8d4e2;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolButton {\n"
"    font: 9pt \"Microsoft YaHei\";\n"
"    color: #2c3e50;\n"
"    background: #ffffff;\n"
"    border: 1px solid #b8c7d8;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"}\n"
"QToolButton:checked {\n"
"    color: #ffffff;\n"
"    background: #3d7ecb;\n"
"    border-color: #3d7ecb;\n"
"}\n"
"QToolButton:disabled {\n"
"    color: #8a98a8;\n"
"    background: #edf1f5;\n"
"    border-color: #d5dde6;\n"
"}")
        self.frame_contour_workflow.setObjectName("frame_contour_workflow")
        self.verticalLayout_workflow = QtWidgets.QVBoxLayout(self.frame_contour_workflow)
        self.verticalLayout_workflow.setContentsMargins(10, 8, 10, 8)
        self.verticalLayout_workflow.setSpacing(6)
        self.verticalLayout_workflow.setObjectName("verticalLayout_workflow")
        self.lb_title = QtWidgets.QLabel(self.frame_contour_workflow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_title.setFont(font)
        self.lb_title.setObjectName("lb_title")
        self.verticalLayout_workflow.addWidget(self.lb_title)
        self.horizontalLayout_workflow_steps = QtWidgets.QHBoxLayout()
        self.horizontalLayout_workflow_steps.setSpacing(6)
        self.horizontalLayout_workflow_steps.setObjectName("horizontalLayout_workflow_steps")
        self.lb_number = QtWidgets.QLabel(self.frame_contour_workflow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(40)
        self.lb_number.setFont(font)
        self.lb_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_number.setObjectName("lb_number")
        self.horizontalLayout_workflow_steps.addWidget(self.lb_number)
        self.verticalLayout_workflow.addLayout(self.horizontalLayout_workflow_steps)
        self.lb_workflow_hint = QtWidgets.QLabel(self.frame_contour_workflow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lb_workflow_hint.setFont(font)
        self.lb_workflow_hint.setWordWrap(True)
        self.lb_workflow_hint.setObjectName("lb_workflow_hint")
        self.verticalLayout_workflow.addWidget(self.lb_workflow_hint)
        self.verticalLayout.addWidget(self.frame_contour_workflow)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_inc = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_inc.sizePolicy().hasHeightForWidth())
        self.pb_inc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.pb_inc.setFont(font)
        self.pb_inc.setObjectName("pb_inc")
        self.horizontalLayout.addWidget(self.pb_inc)
        self.pb_dec = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dec.sizePolicy().hasHeightForWidth())
        self.pb_dec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.pb_dec.setFont(font)
        self.pb_dec.setObjectName("pb_dec")
        self.horizontalLayout.addWidget(self.pb_dec)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_title.setText(_translate("Form", "跨平台应用程序_课堂练习"))
        self.lb_number.setText(_translate("Form", "2026"))
        self.lb_workflow_hint.setText(_translate("Form", "按下左侧按钮，数字递增，右侧按钮数字递减"))
        self.groupBox.setTitle(_translate("Form", "按钮控制区"))
        self.pb_inc.setText(_translate("Form", "数字递增"))
        self.pb_dec.setText(_translate("Form", "数字递减"))
        self.groupBox_2.setTitle(_translate("Form", "滑块进度条控制练习"))
