# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_test02_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_temp_input = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.le_temp_input.setFont(font)
        self.le_temp_input.setObjectName("le_temp_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_temp_input)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_trans_result = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.le_trans_result.setFont(font)
        self.le_trans_result.setObjectName("le_trans_result")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_trans_result)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.pb_trans = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.pb_trans.setFont(font)
        self.pb_trans.setObjectName("pb_trans")
        self.horizontalLayout_4.addWidget(self.pb_trans)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tb_console = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.tb_console.setFont(font)
        self.tb_console.setObjectName("tb_console")
        self.verticalLayout.addWidget(self.tb_console)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "输入温度"))
        self.label_3.setText(_translate("Form", "转换结果"))
        self.pb_trans.setText(_translate("Form", "温度转换"))
